// Authentication API
@AuthAPI_HostAddress = http://localhost:5029/api/Authenticate

// Register User API
POST {{AuthAPI_HostAddress}}/register
Content-Type: application/json

{
  "username": "iamsamit",
  "email": "samit@email.com",
  "password": "Samit@1234"
}

###

// Register Admin API
POST {{AuthAPI_HostAddress}}/register-admin
Content-Type: application/json

{
  "username": "aomadmin",
  "email": "aomadmin@email.com",
  "password": "Adminaom@1234"
}

###

// Login API

POST {{AuthAPI_HostAddress}}/login
Content-Type: application/json

{
  "username": "iamsamit",
  "password": "Samit@1234"
}